### PR TITLE
option to always point the camera upward

### PR DESCRIPTION
**Pull request by tgirod**
This code adds an option to force the camera to always point upward, like in sketchup.

This is done by constraining projRight to stay horizontal (z=0) and projUp upward (z>=0).

This might be a bit heavy-handed, feedback is welcome!

### CODE REVIEW

**Comment by whitequark** [comment]
Well. yeah. this is way too heavy-handed.

**Comment by tgirod** [comment]
The code for the actual movement is better. The code to reset the camera horizontally is not there yet. Ideally I would like to animate the rotation, then move, but I'm not there yet.

**Comment by tgirod** [comment]
I've been working a bit on that, and the more I learn, the more I realize my code is crap, at least in its current form. So I'm closing this pull request for now, until I get something better.

**Comment by whitequark** [comment]
That's uh... quite self-critical of you. I must say I still haven't had any time to look at what Sketchup does.

**Comment by tgirod** [comment]
@whitequark if you find time to look at how sketchup behave on that regard, I'm still available for discussion on this matter!

**Pull request closed without merging**
