### PR TITLE
Use min/max/isnan template in std

### PR DESCRIPTION
**Pull request by wavexx**
I tried to recompile solvespace with g++ 6 and it spewed some errors due to redefinition of min/max.
Since min/max/isnan is available in std, I decided to add an extra check for it and fix the resulting casting errors due to mixed types in the arguments, which should be retro-compatible as well.

I don't think there's a proper way to check for the definition of min/max in c++. AFAIK, all tree should be available via algorithm/cmath since c++98 and gcc 3.x.

I added the extra macro check only because I'm unsure about the situation on windows.

### CODE REVIEW

**Comment by whitequark** [comment]
That's long fixed in `for-upstream`, which is the default branch in this repo, and also the one nightlies are built from.

**Comment by whitequark** [comment]
Or to rephrase, all development currently happens in `for-upstream` and topical branches, master is just the same as jwesthues/solvespace/master.

**Comment by wavexx** [comment]
Noticed just now. I had a cloned repository locally and didn't see activity in a long time.
Thanks.

**Comment by wavexx** [comment]
On Mon, Mar 07 2016, whitequark <notifications@github.com> wrote:
> Or to rephrase, all development currently happens in for-upstream and topical
> branches, master is just the same as jwesthues/solvespace/master.

Just to know, what's the state of for-upstream?
It builds fine, but I just tried extruding something and it crashes.

**Comment by whitequark** [comment]
Works over here. Can you give me the backtrace?

**Comment by wavexx** [comment]
On Mon, Mar 07 2016, whitequark <notifications@github.com> wrote:
> Works over here. Can you give me the backtrace?

Hmm, this=0x0..

Program received signal SIGSEGV, Segmentation fault.
SolveSpace::SBspUv::InsertEdge (this=0x0, ea=..., eb=..., srf=0x323b8d0)
    at /home/ydelia/downloads/src/solvespace/src/srf/boolean.cpp:861
861	    double dea = ScaledSignedDistanceToLine(ea, a, b, srf),
(gdb) bt
#0  SolveSpace::SBspUv::InsertEdge (this=0x0, ea=..., eb=..., srf=0x323b8d0)
    at /home/ydelia/downloads/src/solvespace/src/srf/boolean.cpp:861
#1  0x00000000004fdb57 in SolveSpace::SBspUv::InsertEdge (srf=0x323b8d0, eb=..., ea=..., this=0x32b18d0)
    at /home/ydelia/downloads/src/solvespace/src/srf/boolean.cpp:886
#2  SolveSpace::SBspUv::From (el=el@entry=0x7ffffffe9600, srf=srf@entry=0x323b8d0)
    at /home/ydelia/downloads/src/solvespace/src/srf/boolean.cpp:810
#3  0x000000000050218f in SolveSpace::SSurface::MakeClassifyingBsp (useCurvesFrom=0x0, 
    shell=0x7fffe8c457a0, this=0x323b8d0) at /home/ydelia/downloads/src/solvespace/src/srf/boolean.cpp:776
#4  SolveSpace::SShell::MakeClassifyingBsps (useCurvesFrom=0x0, this=0x7fffe8c457a0)
    at /home/ydelia/downloads/src/solvespace/src/srf/boolean.cpp:768
#5  SolveSpace::SShell::MakeFromBoolean (this=this@entry=0x7fffe8c457c8, a=a@entry=0x7fffe8c324a8, 
    b=b@entry=0x7fffe8c457a0, type=type@entry=10)
    at /home/ydelia/downloads/src/solvespace/src/srf/boolean.cpp:715
#6  0x000000000050340a in SolveSpace::SShell::MakeFromUnionOf (this=this@entry=0x7fffe8c457c8, 
    a=a@entry=0x7fffe8c324a8, b=b@entry=0x7fffe8c457a0)
    at /home/ydelia/downloads/src/solvespace/src/srf/boolean.cpp:12
#7  0x00000000004bdd22 in SolveSpace::Group::GenerateForBoolean<SolveSpace::SShell> (this=0x7fffe8c45650, 
    how=0, outs=0x7fffe8c457c8, thiss=0x7fffe8c457a0, prevs=0x7fffe8c324a8)
    at /home/ydelia/downloads/src/solvespace/src/groupmesh.cpp:172
#8  SolveSpace::Group::GenerateShellAndMesh (this=this@entry=0x7fffe8c45650)
    at /home/ydelia/downloads/src/solvespace/src/groupmesh.cpp:321
#9  0x00000000004a1fea in SolveSpace::SolveSpaceUI::GenerateAll (this=0xa7a900 <SolveSpace::SS>, 
    type=type@entry=SolveSpace::SolveSpaceUI::GENERATE_DIRTY, andFindFree=andFindFree@entry=false, 
    genForBBox=genForBBox@entry=false) at /home/ydelia/downloads/src/solvespace/src/generate.cpp:311
#10 0x00000000004ba6d0 in SolveSpace::Group::MenuGroup (id=<optimized out>)
    at /home/ydelia/downloads/src/solvespace/src/group.cpp:247
#11 0x00007ffff6e6a870 in Gtk::MenuItem_Class::activate_callback(_GtkMenuItem*) ()

**Comment by whitequark** [comment]
Ah yes. This is not my fault, SolveSpace has had invalid C++ in it for years. InsertEdge starts with `if(!this)` and gcc 6 rightfully optimizes that to `if(false)`.

**Comment by whitequark** [comment]
https://github.com/whitequark/solvespace/issues/70.

**Pull request closed without merging**
